name       : deja-dup
version    : '35.6'
release    : 10
source     :
    - https://launchpad.net/deja-dup/36/35.6/+download/deja-dup-35.6.tar.xz : a6a850425c3fcb535f5411cfeab39c3edef976cd5fa9e832f8f2943b051d6292
license    : GPL-3.0
component  : desktop
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(packagekit-glib2)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - duplicity
setup      : |
    %meson_configure
build      : |
    ninja -j1 -C solusBuildDir
install    : |
    %meson_install
