name       : deja-dup
version    : 34.3
release    : 7
source     :
    - https://launchpad.net/deja-dup/34/34.3/+download/deja-dup-34.3.tar.xz : c90a098c2b60fa73d6bcc51d7f8a33fc7c279f2556b677145d50ad0b83c90cf7
license    : GPL-3.0
component  : desktop
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(packagekit-glib2)
    - itstool
    - vala
rundeps    :
    - duplicity
setup      : |
    %cmake \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/libexec/deja-dup/ .
build      : |
    %make
install    : |
    %make_install
