name       : deja-dup
version    : '40.5'
release    : 19
source     :
    - https://gitlab.gnome.org/World/deja-dup/-/archive/40.5/deja-dup-40.5.tar.bz2 : b60d8cc5f024cf0cdea12bbb7ef62f2b304dc6b3ef87d337aae92afbb535f8ca
license    : GPL-3.0-or-later
component  : system.utils
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - desktop-file-utils
    - duplicity
    - gvfs-devel
    - itstool
    - vala
rundeps    :
    - duplicity
    - gvfs
setup      : |
    %meson_configure
build      : |
    %ninja_build -j1
install    : |
    %ninja_install
