name       : deja-dup
version    : '38.3'
release    : 16
source     :
    - https://gitlab.gnome.org/World/deja-dup/-/archive/38.3/deja-dup-38.3.tar.gz : ef1c086b85761d88713b0316de842994e58c2c1e2585c4e3f0f933f7610b0132
license    : GPL-3.0-or-later
component  : system.utils
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - duplicity
setup      : |
    %meson_configure
build      : |
    %meson_build -j1
install    : |
    %meson_install
