name       : deja-dup
version    : 34.1
release    : 2
source     :
    - https://launchpad.net/deja-dup/34/34.1/+download/deja-dup-34.1.tar.xz : c5469aa6c4d86e5cfc34664549b84b8cc555ece95551e1147029f738a877e551
license    : GPL-3.0
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
rundeps    :
     - duplicity
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(libpeas-1.0)
    - itstool
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
