name       : deja-dup
version    : '43.3'
release    : 28
source     :
    - https://gitlab.gnome.org/World/deja-dup/-/archive/43.3/deja-dup-43.3.tar.gz : 8d6ef2252bf62363d632435e64f7fe1614e736068d8b529a2ba75de484ea8862
homepage   : https://wiki.gnome.org/Apps/DejaDup
license    : GPL-3.0-or-later
component  : system.utils
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(wayland-client)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - duplicity
    - gvfs
    - python-pydrive2
setup      : |
    %meson_configure -Dpydrive_pkgs=python-pydrive2
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
