name       : deja-dup
version    : '42.9'
release    : 25
source     :
    - https://gitlab.gnome.org/World/deja-dup/-/archive/42.9/deja-dup-42.9.tar.gz : bc1db2b7949b3e313bb952255e4e93a764371c9d0920cfa3d59172036dfcdb70
homepage   : https://wiki.gnome.org/Apps/DejaDup
license    : GPL-3.0-or-later
component  : system.utils
summary    : Déjà Dup backup tool
description: |
    Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - duplicity
    - gvfs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
